#ifndef __BLE_SPP_SERVER_DEMO_H
#define __BLE_SPP_SERVER_DEMO_H

/* SPP Service 属性表索引 */
enum {
    SPP_IDX_SVC,
    SPP_IDX_SPP_DATA_RECV_CHAR,
    SPP_IDX_SPP_DATA_RECV_VAL,
    SPP_IDX_SPP_DATA_NOTIFY_CHAR,
    SPP_IDX_SPP_DATA_NTY_VAL,
    SPP_IDX_SPP_DATA_NTF_CFG,
    SPP_IDX_SPP_COMMAND_CHAR,
    SPP_IDX_SPP_COMMAND_VAL,
    SPP_IDX_SPP_STATUS_CHAR,
    SPP_IDX_SPP_STATUS_VAL,
    SPP_IDX_SPP_STATUS_CFG,
#ifdef SUPPORT_HEARTBEAT
    SPP_IDX_SPP_HEARTBEAT_CHAR,
    SPP_IDX_SPP_HEARTBEAT_VAL,
    SPP_IDX_SPP_HEARTBEAT_CFG,
#endif
    SPP_IDX_NB
};

#define SPP_DATA_MAX_LEN    20
#define SPP_CMD_MAX_LEN     10
#define SPP_STATUS_MAX_LEN  10

#endif
