/*
 * SPDX-FileCopyrightText: 2022-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_ANIMATION_FILES           5
#define MMAP_ANIMATION_CHECKSUM        0x1222

enum MMAP_ANIMATION_LISTS {
    MMAP_ANIMATION_ASK_JSON = 0,        /*!< ask.json */
    MMAP_ANIMATION_FISH_JSON = 1,        /*!< fish.json */
    MMAP_ANIMATION_LOOK_JSON = 2,        /*!< look.json */
    MMAP_ANIMATION_SPEAK_JSON = 3,        /*!< speak.json */
    MMAP_ANIMATION_THINK_JSON = 4,        /*!< think.json */
};
